spring:
    main:
        allow-bean-definition-overriding: true 
    application:
        name: authen
    data:
        redis:
            repositories:
                enabled: true
            host: localhost
            port: 6379
grpc:
    client:
        user-service:
            address: localhost:7091
            negotiationType: plaintext
        enabled: true

