server:
  port: 9092
spring:
  application:
    name: authen
  redis:
    host: localhost
    port: 6379
  main:
      allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:54321/auth
    username: postgres
    password: user123
  jpa:
    hibernate:
      ddl-auto: update

grpc:
    client:
        user-service:
            address: localhost:7091
            negotiationType: plaintext
    server:
        port: 7092